{"name": "测试失败", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 0", "trace": "self = <case.test_api.TestApi object at 0x000001F21BD76908>\n\n    @allure.title(\"测试失败\")\n    @pytest.mark.flaky(reruns=2, reruns_delay=3)\n    def test_fail(self):\n        with allure.step(\"失败用例1\"):\n            print(\"失败用例1失败用例1失败用例1失败用例1失败用例1\")\n            assert 1 == 1\n    \n        with allure.step(\"失败用例2\"):\n            print(\"失败用例2失败用例2失败用例2失败用例2失败用例2失败用例2\")\n>           assert 1 == 0\nE           assert 1 == 0\n\ncase\\test_api.py:166: AssertionError"}, "steps": [{"name": "失败用例1", "status": "passed", "start": 1684067891400, "stop": 1684067891400}, {"name": "失败用例2", "status": "failed", "statusDetails": {"message": "AssertionError: assert 1 == 0\n", "trace": "  File \"D:\\PycharmProjects\\电商接口自动化项目\\case\\test_api.py\", line 166, in test_fail\n    assert 1 == 0\n"}, "start": 1684067891401, "stop": 1684067891401}], "start": 1684067891400, "stop": 1684067891402, "uuid": "7230888b-e880-4b99-9128-8ed8291f1e5a", "historyId": "bfed40cb5125b32353e101be98dbe867", "testCaseId": "357573bd99f54799b97d0ad69baff7b9", "fullName": "case.test_api.TestApi#test_fail", "labels": [{"name": "epic", "value": "user接口测试"}, {"name": "tag", "value": "flaky(reruns=2, reruns_delay=3)"}, {"name": "parentSuite", "value": "case"}, {"name": "suite", "value": "test_api"}, {"name": "subSuite", "value": "TestApi"}, {"name": "host", "value": "V_PEARLHON-NBIO"}, {"name": "thread", "value": "21164-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "case.test_api"}]}